// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/edgarSucre/moca/internal/controller (interfaces: Usecase)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	domain "github.com/edgarSucre/moca/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetMortgagePayment mocks base method.
func (m *MockUsecase) GetMortgagePayment(arg0 domain.Mortgage) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMortgagePayment", arg0)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMortgagePayment indicates an expected call of GetMortgagePayment.
func (mr *MockUsecaseMockRecorder) GetMortgagePayment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMortgagePayment", reflect.TypeOf((*MockUsecase)(nil).GetMortgagePayment), arg0)
}
